### ISSUE TITLE
Creation date missing from a repository

### ISSUE THREAD

**Issue by duianto** [lvarayut/github-date-of-creation#9]
This repository doesn't show the creation date.
https://github.com/hasu/emacs-ob-racket/

![chrome_2020-10-22_18-21-02](https://user-images.githubusercontent.com/13420573/96901380-77f19080-1493-11eb-8ff9-1e44a11d2ab7.png)

The issue is observed both when one is logged in or in a incognito tab (the extension is also enabled in incognito mode).

This is the first time I've seen this issue.

The creation date is shown as expected in other repositories, both when one is logged in or in incognito mode.

For example this repository:
https://github.com/lvarayut/github-date-of-creation

![chrome_2020-10-22_18-21-18](https://user-images.githubusercontent.com/13420573/96901491-a40d1180-1493-11eb-8b62-dad6d418ef55.png)

**Comment by lvarayut** [comment]
Thanks @duianto for reporting the issue.

**Comment by fabianoriccardi** [comment]
@lvarayut  the issue is already solved by the most recent commit [8cc6bbd](https://github.com/lvarayut/github-date-of-creation/commit/8cc6bbd1376069af3598f6093109c4b9eefd0e64) on the main branch. I think you forget to release the updated version on Chrome Extension Store. 

@duianto remove the final `/' from your url and the repo page will show the creation date.

**Comment by duianto** [comment]
@fabianoriccardi Thanks for the workaround until the extension is updated.

**Comment by lvarayut** [comment]
Thanks @fabianoriccardi for the reminder. I've just updated the version and tested with the repository that @duianto reported, it works as expected now.
